// Auth-Types

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "LOAD_USER_SUCCESS";
export const USER_LOADED_FAIL = "LOAD_USER_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";

// Google-Ads-Types
export const GOOGLE_ADS_LOAD_HIERARCHY_SUCCESS = "GOOGLE_ADS_LOAD_HIERARCHY_SUCCESS";
export const GOOGLE_ADS_LOAD_HIERARCHY_FAIL = "GOOGLE_ADS_LOAD_HIERARCHY_FAIL";

// Fb Ads types
export const FB_ADS_LOAD_ACT_LIST_SUCCESS = "FB_ADS_LOAD_ACT_LIST_SUCCESS";
export const FB_ADS_LOAD_ACT_LIST_FAIL = "FB_ADS_LOAD_ACT_LIST_FAIL";

// Fb Insights types
export const FB_INSIGHTS_LOAD_PAGES_LIST_SUCCESS = "FB_INSIGHTS_LOAD_PAGES_LIST_SUCCESS";
export const FB_INSIGHTS_LOAD_PAGES_LIST_FAIL = "FB_INSIGHTS_LOAD_PAGES_LIST_FAIL";

// Google Analytics types
export const GA4_LOAD_ACT_LIST_SUCCESS = "GA4_LOAD_ACT_LIST_SUCCESS";
export const GA4_LOAD_ACT_LIST_FAIL = "GA4_LOAD_ACT_LIST_FAIL";

// Google Search Console types
export const SEARCH_CONSOLE_LOAD_ACT_LIST_SUCCESS = "SEARCH_CONSOLE_LOAD_ACT_LIST_SUCCESS";
export const SEARCH_CONSOLE_LOAD_ACT_LIST_FAIL = "SEARCH_CONSOLE_LOAD_ACT_LIST_FAIL";

// Bing Ads types
export const BING_ADS_LOAD_ACT_LIST_SUCCESS = "BING_ADS_LOAD_ACT_LIST_SUCCESS";
export const BING_ADS_LOAD_ACT_LIST_FAIL = "BING_ADS_LOAD_ACT_LIST_FAIL";

// IG Profile types
export const IG_INSIGHTS_LOAD_PROFILES_LIST_SUCCESS = "IG_INSIGHTS_LOAD_PROFILES_LIST_SUCCESS";
export const IG_INSIGHTS_LOAD_PROFILES_LIST_FAIL = "IG_INSIGHTS_LOAD_PROFILES_LIST_FAIL";

// LinkedIn Ads types
export const LINKEDIN_ADS_LOAD_ACT_LIST_SUCCESS = "LINKEDIN_ADS_LOAD_ACT_LIST_SUCCESS";
export const LINKEDIN_ADS_LOAD_ACT_LIST_FAIL = "LINKEEDIN_ADS_LOAD_ACT_LIST_FAIL";

// Workspace types

export const WORKSPACE_LOAD_DATA_SUCCESS = "WORKSPACE_LOAD_DATA_SUCCESS";
export const WORKSPACE_LOAD_DATA_FAIL = "WORKSPACE_LOAD_DATA_FAIL";
export const UPDATE_WORKSPACE_DATA = "UPDATE_WORKSPACE_DATA";

export const LOAD_SUBSCRIPTION_DATA_SUCCESS = "LOAD_SUBSCRIPTION_DATA_SUCCESS";
export const LOAD_SUBSCRIPTION_DATA_FAIL = "LOAD_SUBSCRIPTION_DATA_FAIL";

export const LOAD_CONNECTED_SOURCES_SUCCESS = "LOAD_CONNECTED_SOURCES_SUCCESS";
export const LOAD_CONNECTED_SOURCES_FAIL = "LOAD_CONNECTED_SOURCES_FAIL";