
const images :{[key:string]:string}  = {
  brandLogo: require("../../../public/assets/images/brandLogo.svg"),
  brandLogoWhite: require("../../../public/assets/images/brandLogoWhite.svg"),
  rightArrow: require("../../../public/assets/images/rightArrow.svg"),
  adzviserBoxOne: require("../../../public/assets/images/adzViserOne.png"),
  adzviserBoxTwo: require("../../../public/assets/images/adzViserTwo.png"),
  ellipse: require("../../../public/assets/images/ellipse.svg"),
  problem: require("../../../public/assets/images/problem.png"),
  adwords: require("../../../public/assets/images/adwords.png"),
  search: require("../../../public/assets/images/search.svg"),
  receiveQuestion: require("../../../public/assets/images/receiveQuestion.png"),
  channel: require("../../../public/assets/images/channel.svg"),
  cancel: require("../../../public/assets/images/cancel.svg"),
  privacy: require("../../../public/assets/images/privacy.svg"),
  bean: require("../../../public/assets/images/bean.png"),
  upDown: require("../../../public/assets/images/upDown.svg"),
  solemates: require("../../../public/assets/images/solemates.png"),
  connect: require("../../../public/assets/images/connect.png"),
  share: require("../../../public/assets/images/share.png"),
  Search: require("../../../public/assets/images/search.png"),
  benefit: require("../../../public/assets/images/benefit.png"),
  macBook: require("../../../public/assets/images/macBook.png"),
  searchCancel: require("../../../public/assets/images/cancelNew.svg"),
  adwordsLogo: require("../../../public/assets/images/adwordsLogo.svg"),
  facebook: require("../../../public/assets/images/facebook.svg"),
  instagram: require("../../../public/assets/images/instagramLogo.svg"),
  linkedin: require("../../../public/assets/images/linkedin.svg"),
  loginBg: require("../../../public/assets/images/loginBg.png"),
  ga4: require("../../../public/assets/images/ga4.svg"),
  searchConsole: require("../../../public/assets/images/searchConsole.svg"),
  bingAds: require("../../../public/assets/images/bingLogo.svg"),
  tikTokAds: require("../../../public/assets/images/tiktokAds.png"),
  eyeIcon: require("../../../public/assets/images/eyeIcon.svg"),
  hideeyeIcon: require("../../../public/assets/images/hideEyeIcon.svg"),
  emailIcon: require("../../../public/assets/images/emailIcon.svg"),
  userIcon: require("../../../public/assets/images/userIcon.svg"),
  tickIcon: require("../../../public/assets/images/tickIcon.svg"),
  adzviserLogo: require("../../../public/assets/images/adzviserLogo.svg"),
  chatgptLogo: require("../../../public/assets/images/chatGpt.svg"),
  chatgptCombo: require("../../../public/assets/images/chatgptCombo.svg"),
  addIcon: require("../../../public/assets/images/addIcon.svg"),
  logoutIcon: require("../../../public/assets/images/logout.svg"),
  closeIcon: require("../../../public/assets/images/Union.svg"),
  actionbg: require("../../../public/assets/images/actionbg.svg"),
  apple: require("../../../public/assets/images/apple.svg"),
  tut: require("../../../public/assets/images/tut.svg"),
  bannerbg: require("../../../public/assets/images/bannerbg.svg"),
};

export default images;
